name: rollcall
description: A sample web application
dependencies:
  angular: 0.11.0
  bootjack: any
  browser: any
  intl: any
  web_components: any
  route_hierarchical: '>=0.4.18 <0.5.0'
  dabl:
    path: ../dabl-dart
dev_dependencies:
  unittest: any
transformers:
- angular
