name: RollCall
description: A sample web application
dependencies:
  angular: 0.9.8
  bootjack: any
  browser: any
  intl: any
  shadow_dom: any
  dabl:
    path: ../dabl-dart
dev_dependencies:
  unittest: any
